<?php

namespace busBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * busRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class busRepository extends EntityRepository
{
}
